cat > /home/claude/war-room/js/dsa.js << 'EOF'
const DSA_PLAN = {
  totalDays: 90,
  topics: [
    { step:1,  title:"Basics",                           days:"1–6",   icon:"🔢", color:"#38bdf8",
      subtopics:[
        {id:"b1",  title:"Time & Space Complexity",          day:1, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/time-and-space-complexity/"},
        {id:"b2",  title:"Pattern Problems (1-22)",          day:1, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/patterns-a2z/"},
        {id:"b3",  title:"C++ STL / Python Collections",     day:2, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/c-stl/"},
        {id:"b4",  title:"User Input / Output",              day:2, difficulty:"Easy",   link:"https://takeuforward.org"},
        {id:"b5",  title:"Functions & Recursion Basics",     day:3, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/recursion-explained/"},
        {id:"b6",  title:"Basic Maths — Count Digits",       day:3, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/count-digits-in-a-number/"},
        {id:"b7",  title:"Basic Maths — Reverse Number",     day:3, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/reverse-a-number/"},
        {id:"b8",  title:"Basic Maths — Check Palindrome",   day:4, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/check-if-a-number-is-palindrome-or-not/"},
        {id:"b9",  title:"Basic Maths — GCD / HCF",          day:4, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/find-gcd-of-two-numbers/"},
        {id:"b10", title:"Basic Maths — Armstrong Numbers",  day:4, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/check-if-a-number-is-armstrong-number-or-not/"},
        {id:"b11", title:"Basic Maths — Print All Divisors", day:5, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/print-all-divisors-of-a-number/"},
        {id:"b12", title:"Basic Maths — Check Prime",        day:5, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/check-if-a-number-is-prime-or-not/"},
        {id:"b13", title:"Recursion — Fibonacci",            day:5, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/print-fibonacci-series/"},
        {id:"b14", title:"Recursion — Factorial",            day:6, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/find-factorial-of-a-number-recursive/"},
        {id:"b15", title:"Recursion — Sum of N Numbers",     day:6, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/sum-of-first-n-natural-numbers/"},
        {id:"b16", title:"Hashing — Frequency Count",        day:6, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/hashing-in-c/"},
      ]},
    { step:2,  title:"Sorting Algorithms",               days:"7–9",   icon:"↕️", color:"#818cf8",
      subtopics:[
        {id:"s1", title:"Selection Sort",          day:7, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/selection-sort-algorithm/"},
        {id:"s2", title:"Bubble Sort",             day:7, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/bubble-sort-algorithm/"},
        {id:"s3", title:"Insertion Sort",          day:7, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/insertion-sort-algorithm/"},
        {id:"s4", title:"Merge Sort",              day:8, difficulty:"Medium", link:"https://takeuforward.org/data-structure/merge-sort-algorithm/"},
        {id:"s5", title:"Quick Sort",              day:8, difficulty:"Medium", link:"https://takeuforward.org/data-structure/quick-sort-algorithm/"},
        {id:"s6", title:"Recursive Bubble Sort",   day:9, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/recursive-bubble-sort-algorithm/"},
        {id:"s7", title:"Recursive Insertion Sort",day:9, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/recursive-insertion-sort/"},
      ]},
    { step:3,  title:"Arrays",                           days:"10–22", icon:"📊", color:"#34d399",
      subtopics:[
        {id:"a1",  title:"Largest Element in Array",           day:10, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/find-the-largest-element-in-an-array/"},
        {id:"a2",  title:"Second Largest Element",             day:10, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/find-second-smallest-and-second-largest-element/"},
        {id:"a3",  title:"Check Sorted Array",                 day:10, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/check-if-an-array-is-sorted/"},
        {id:"a4",  title:"Remove Duplicates (Sorted)",         day:11, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/remove-duplicates-in-place-from-sorted-array/"},
        {id:"a5",  title:"Left Rotate Array by One",           day:11, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/left-rotate-the-array-by-one/"},
        {id:"a6",  title:"Rotate Array by K Places",           day:11, difficulty:"Medium", link:"https://takeuforward.org/data-structure/rotate-array-by-k-places/"},
        {id:"a7",  title:"Move Zeroes to End",                 day:12, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/move-all-zeros-to-the-end-of-the-array/"},
        {id:"a8",  title:"Linear Search",                      day:12, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/linear-search-in-c/"},
        {id:"a9",  title:"Union of Two Sorted Arrays",         day:12, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/union-of-two-sorted-arrays/"},
        {id:"a10", title:"Intersection of Two Sorted Arrays",  day:13, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/intersection-of-two-sorted-arrays/"},
        {id:"a11", title:"Missing Number",                     day:13, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/find-the-missing-number-in-an-array/"},
        {id:"a12", title:"Max Consecutive Ones",               day:13, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/count-maximum-consecutive-ones-in-the-array/"},
        {id:"a13", title:"Find the Number Appearing Once",     day:14, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/find-the-number-that-appears-once-and-the-other-numbers-twice/"},
        {id:"a14", title:"Longest Sub-Array with Sum K",       day:14, difficulty:"Medium", link:"https://takeuforward.org/data-structure/longest-subarray-with-sum-k-postives-and-0s/"},
        {id:"a15", title:"Two Sum",                            day:15, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/two-sum-check-if-a-pair-with-given-sum-exists-in-array/"},
        {id:"a16", title:"Sort 0s 1s 2s (Dutch Flag)",        day:15, difficulty:"Medium", link:"https://takeuforward.org/data-structure/sort-an-array-of-0s-1s-and-2s/"},
        {id:"a17", title:"Majority Element (>n/2)",            day:15, difficulty:"Medium", link:"https://takeuforward.org/data-structure/find-the-majority-element-that-occurs-more-than-n-2-times/"},
        {id:"a18", title:"Kadane's Algorithm",                 day:16, difficulty:"Medium", link:"https://takeuforward.org/data-structure/kadanes-algorithm-maximum-subarray-sum/"},
        {id:"a19", title:"Best Time to Buy/Sell Stock",        day:16, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/stock-buy-and-sell/"},
        {id:"a20", title:"Rearrange +ve and -ve Numbers",      day:17, difficulty:"Medium", link:"https://takeuforward.org/data-structure/rearrange-array-elements-by-sign/"},
        {id:"a21", title:"Next Permutation",                   day:17, difficulty:"Medium", link:"https://takeuforward.org/data-structure/next_permutation-find-next-lexicographically-greater-permutation/"},
        {id:"a22", title:"Leaders in Array",                   day:17, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/leaders-in-an-array/"},
        {id:"a23", title:"Longest Consecutive Sequence",       day:18, difficulty:"Medium", link:"https://takeuforward.org/data-structure/longest-consecutive-sequence-in-an-array/"},
        {id:"a24", title:"Set Matrix Zeroes",                  day:18, difficulty:"Medium", link:"https://takeuforward.org/data-structure/set-matrix-zero/"},
        {id:"a25", title:"Rotate Matrix 90°",                  day:18, difficulty:"Medium", link:"https://takeuforward.org/data-structure/rotate-image-by-90-degree/"},
        {id:"a26", title:"Spiral Traversal of Matrix",         day:19, difficulty:"Medium", link:"https://takeuforward.org/data-structure/spiral-traversal-of-matrix/"},
        {id:"a27", title:"Count Subarrays with XOR = K",       day:19, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/number-of-subarrays-with-xor-k/"},
        {id:"a28", title:"Merge Overlapping Intervals",        day:19, difficulty:"Medium", link:"https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/"},
        {id:"a29", title:"Merge Two Sorted Arrays (No Space)", day:20, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/merge-two-sorted-arrays-without-extra-space/"},
        {id:"a30", title:"Find Duplicate Number",              day:20, difficulty:"Medium", link:"https://takeuforward.org/data-structure/find-the-duplicate-in-an-array-of-n1-integers/"},
        {id:"a31", title:"Missing and Repeating Number",       day:20, difficulty:"Medium", link:"https://takeuforward.org/data-structure/find-the-repeating-and-missing-numbers/"},
        {id:"a32", title:"Count Inversions",                   day:21, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/count-inversions-in-an-array/"},
        {id:"a33", title:"Reverse Pairs",                      day:21, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/count-reverse-pairs/"},
        {id:"a34", title:"Maximum Product Subarray",           day:22, difficulty:"Medium", link:"https://takeuforward.org/data-structure/maximum-product-subarray-in-an-array/"},
      ]},
    { step:4,  title:"Binary Search",                    days:"23–29", icon:"🔍", color:"#f59e0b",
      subtopics:[
        {id:"bs1",  title:"Binary Search (Iterative + Recursive)", day:23, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/binary-search-explained/"},
        {id:"bs2",  title:"Lower/Upper Bound",                     day:23, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/implement-lower-bound/"},
        {id:"bs3",  title:"Search Insert Position",                day:23, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/search-insert-position/"},
        {id:"bs4",  title:"Floor and Ceil in Sorted Array",        day:24, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/implement-ceil-the-floor/"},
        {id:"bs5",  title:"First and Last Occurrence",             day:24, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/first-and-last-occurrences-in-array/"},
        {id:"bs6",  title:"Count in Sorted Array",                 day:24, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/count-occurrences-in-sorted-array/"},
        {id:"bs7",  title:"Search in Rotated Sorted Array",        day:25, difficulty:"Medium", link:"https://takeuforward.org/data-structure/search-element-in-a-rotated-sorted-array/"},
        {id:"bs8",  title:"Search in Rotated Array II",            day:25, difficulty:"Medium", link:"https://takeuforward.org/data-structure/search-in-rotated-sorted-array-ii/"},
        {id:"bs9",  title:"Minimum in Rotated Sorted Array",       day:25, difficulty:"Medium", link:"https://takeuforward.org/data-structure/minimum-element-in-rotated-sorted-array/"},
        {id:"bs10", title:"Find Peak Element",                     day:26, difficulty:"Medium", link:"https://takeuforward.org/data-structure/peak-element-in-array/"},
        {id:"bs11", title:"Sqrt(x) using Binary Search",           day:26, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/find-square-root-of-a-number-in-log-n/"},
        {id:"bs12", title:"Kth Missing Positive Number",           day:26, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/kth-missing-positive-number/"},
        {id:"bs13", title:"Koko Eating Bananas",                   day:27, difficulty:"Medium", link:"https://takeuforward.org/data-structure/koko-eating-bananas/"},
        {id:"bs14", title:"Minimum Days to Make Bouquets",         day:27, difficulty:"Medium", link:"https://takeuforward.org/data-structure/minimum-days-to-make-m-bouquets/"},
        {id:"bs15", title:"Find Smallest Divisor",                 day:27, difficulty:"Medium", link:"https://takeuforward.org/data-structure/find-the-smallest-divisor-given-a-threshold/"},
        {id:"bs16", title:"Capacity to Ship Packages",             day:28, difficulty:"Medium", link:"https://takeuforward.org/data-structure/capacity-to-ship-packages-within-d-days/"},
        {id:"bs17", title:"Kth Element of Two Sorted Arrays",      day:28, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/k-th-element-of-two-sorted-arrays/"},
        {id:"bs18", title:"Median of Two Sorted Arrays",           day:29, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/median-of-two-sorted-arrays/"},
        {id:"bs19", title:"Minimize Max Distance to Gas Station",  day:29, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/minimize-maximum-distance-between-gas-stations/"},
      ]},
    { step:5,  title:"Strings",                          days:"30–34", icon:"📝", color:"#fb7185",
      subtopics:[
        {id:"st1",  title:"Reverse Words in a String",     day:30, difficulty:"Medium", link:"https://takeuforward.org/data-structure/reverse-words-in-a-string/"},
        {id:"st2",  title:"Longest Palindromic Substring", day:30, difficulty:"Medium", link:"https://takeuforward.org/data-structure/longest-palindromic-substring/"},
        {id:"st3",  title:"Roman to Integer",              day:30, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/roman-to-integer/"},
        {id:"st4",  title:"Integer to Roman",              day:31, difficulty:"Medium", link:"https://takeuforward.org/data-structure/integer-to-roman/"},
        {id:"st5",  title:"Implement strStr (KMP)",        day:31, difficulty:"Medium", link:"https://takeuforward.org/data-structure/implement-strstr-using-kmp-algorithm/"},
        {id:"st6",  title:"Longest Common Prefix",         day:31, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/longest-common-prefix-string-amongst-an-array-of-strings/"},
        {id:"st7",  title:"Valid Anagram",                 day:32, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/check-whether-two-strings-are-anagram-of-each-other/"},
        {id:"st8",  title:"Count and Say",                 day:32, difficulty:"Medium", link:"https://takeuforward.org/data-structure/count-and-say/"},
        {id:"st9",  title:"Compare Version Numbers",       day:32, difficulty:"Medium", link:"https://leetcode.com/problems/compare-version-numbers/"},
        {id:"st10", title:"Rabin Karp Algorithm",          day:33, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/rabin-karp-algorithm/"},
        {id:"st11", title:"Z-Algorithm",                   day:33, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/z-algorithm/"},
        {id:"st12", title:"KMP Algorithm",                 day:34, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/kmp-algorithm/"},
      ]},
    { step:6,  title:"Linked Lists",                     days:"35–43", icon:"🔗", color:"#a78bfa",
      subtopics:[
        {id:"ll1",  title:"Introduction — SLL & DLL",              day:35, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/introduction-to-linked-list/"},
        {id:"ll2",  title:"Insertion in Linked List",              day:35, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/learn-insertions-in-doubly-linked-list/"},
        {id:"ll3",  title:"Delete Last Node of Linked List",       day:35, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/delete-last-node-of-linked-list/"},
        {id:"ll4",  title:"Find Length of Linked List",            day:36, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/length-of-a-linked-list/"},
        {id:"ll5",  title:"Reverse Linked List",                   day:36, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/reverse-a-linked-list/"},
        {id:"ll6",  title:"Middle of Linked List",                 day:36, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/find-middle-element-in-a-linked-list/"},
        {id:"ll7",  title:"Detect Cycle in Linked List",           day:37, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/detect-a-cycle-in-a-linked-list/"},
        {id:"ll8",  title:"Find Start of Cycle",                   day:37, difficulty:"Medium", link:"https://takeuforward.org/data-structure/starting-point-of-loop-in-a-linked-list/"},
        {id:"ll9",  title:"Check Palindrome Linked List",          day:37, difficulty:"Medium", link:"https://takeuforward.org/data-structure/check-if-a-linked-list-is-palindrome/"},
        {id:"ll10", title:"Segregate Odd/Even Nodes",              day:38, difficulty:"Medium", link:"https://takeuforward.org/data-structure/odd-even-linked-list/"},
        {id:"ll11", title:"Remove Nth Node from End",              day:38, difficulty:"Medium", link:"https://takeuforward.org/data-structure/remove-nth-node-from-the-end-of-a-linked-list/"},
        {id:"ll12", title:"Delete Middle Node",                    day:38, difficulty:"Medium", link:"https://takeuforward.org/data-structure/delete-middle-node-of-a-linked-list/"},
        {id:"ll13", title:"Sort Linked List (Merge Sort)",         day:39, difficulty:"Medium", link:"https://takeuforward.org/data-structure/sort-linked-list/"},
        {id:"ll14", title:"Sort a LL of 0s 1s 2s",                day:39, difficulty:"Medium", link:"https://takeuforward.org/data-structure/sort-linked-list-of-0s-1s-2s/"},
        {id:"ll15", title:"Find Intersection of Two LLs",         day:39, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/find-intersection-of-two-linked-lists/"},
        {id:"ll16", title:"Add 1 to a Linked List Number",        day:40, difficulty:"Medium", link:"https://takeuforward.org/data-structure/add-1-to-a-number-represented-as-linked-list/"},
        {id:"ll17", title:"Add Two Numbers as Linked Lists",       day:40, difficulty:"Medium", link:"https://takeuforward.org/data-structure/add-two-numbers-represented-as-linked-lists/"},
        {id:"ll18", title:"LRU Cache",                             day:40, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/design-lru-cache/"},
        {id:"ll19", title:"Rotate Linked List",                    day:41, difficulty:"Medium", link:"https://takeuforward.org/data-structure/rotate-a-linked-list/"},
        {id:"ll20", title:"Flattening a Linked List",              day:41, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/flattening-a-linked-list/"},
        {id:"ll21", title:"Clone LL with Random Pointer",         day:42, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/clone-linked-list-with-random-and-next-pointer/"},
        {id:"ll22", title:"Reverse LL in groups of K",             day:42, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/reverse-linked-list-in-groups-of-size-k/"},
        {id:"ll23", title:"Merge K Sorted Linked Lists",           day:43, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/merge-k-sorted-lists/"},
      ]},
    { step:7,  title:"Recursion & Backtracking",         days:"44–50", icon:"🔄", color:"#f59e0b",
      subtopics:[
        {id:"r1",  title:"Subset Sums",                   day:44, difficulty:"Medium", link:"https://takeuforward.org/data-structure/subset-sum-sum-of-all-subsets/"},
        {id:"r2",  title:"Subsets II (with duplicates)",  day:44, difficulty:"Medium", link:"https://takeuforward.org/data-structure/subsets-ii-print-all-the-unique-subsets/"},
        {id:"r3",  title:"Combination Sum I",             day:45, difficulty:"Medium", link:"https://takeuforward.org/data-structure/combination-sum-1/"},
        {id:"r4",  title:"Combination Sum II",            day:45, difficulty:"Medium", link:"https://takeuforward.org/data-structure/combination-sum-ii-find-all-unique-combinations/"},
        {id:"r5",  title:"Palindrome Partitioning",       day:45, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/palindrome-partitioning/"},
        {id:"r6",  title:"Permutation Sequence",          day:46, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/find-k-th-permutation-sequence/"},
        {id:"r7",  title:"Print All Permutations",        day:46, difficulty:"Medium", link:"https://takeuforward.org/data-structure/print-all-permutations-of-a-string-array/"},
        {id:"r8",  title:"N Queens",                      day:47, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/n-queen-problem-return-all-distinct-solutions-to-the-n-queens-puzzle/"},
        {id:"r9",  title:"Sudoku Solver",                 day:47, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/sudoku-solver/"},
        {id:"r10", title:"M-Coloring Problem",            day:48, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/m-coloring-problem/"},
        {id:"r11", title:"Rat in a Maze",                 day:48, difficulty:"Medium", link:"https://takeuforward.org/data-structure/rat-in-a-maze/"},
        {id:"r12", title:"Word Break II",                 day:49, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/word-break-ii/"},
        {id:"r13", title:"Reverse Stack using Recursion", day:49, difficulty:"Medium", link:"https://takeuforward.org/data-structure/reverse-a-stack-using-recursion/"},
        {id:"r14", title:"Sort Stack using Recursion",    day:50, difficulty:"Medium", link:"https://takeuforward.org/data-structure/sort-a-stack-using-recursion/"},
      ]},
    { step:8,  title:"Stacks & Queues",                  days:"51–56", icon:"📚", color:"#06d6a0",
      subtopics:[
        {id:"sq1",  title:"Implement Stack using Array",        day:51, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/implement-stack-using-arrays/"},
        {id:"sq2",  title:"Implement Queue using Array",        day:51, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/implement-queue-using-array/"},
        {id:"sq3",  title:"Implement Stack using Queue",        day:51, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/implement-stack-using-single-queue/"},
        {id:"sq4",  title:"Implement Queue using Stack",        day:52, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/implement-queue-using-stack/"},
        {id:"sq5",  title:"Valid Parentheses",                  day:52, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/valid-parentheses/"},
        {id:"sq6",  title:"Next Greater Element",               day:52, difficulty:"Medium", link:"https://takeuforward.org/data-structure/next-greater-element-using-stack/"},
        {id:"sq7",  title:"Sort a Stack",                       day:53, difficulty:"Medium", link:"https://takeuforward.org/data-structure/sort-a-stack-using-recursion/"},
        {id:"sq8",  title:"Next Smaller Element",               day:53, difficulty:"Medium", link:"https://takeuforward.org/data-structure/next-smaller-element/"},
        {id:"sq9",  title:"LFU Cache",                          day:53, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/design-lfu-cache/"},
        {id:"sq10", title:"Largest Rectangle in Histogram",     day:54, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/largest-rectangle-in-histogram/"},
        {id:"sq11", title:"Maximal Rectangle in Binary Matrix", day:54, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/maximal-rectangle-area-in-a-binary-matrix/"},
        {id:"sq12", title:"Sliding Window Maximum",             day:55, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/sliding-window-maximum/"},
        {id:"sq13", title:"Online Stock Span",                  day:55, difficulty:"Medium", link:"https://takeuforward.org/data-structure/online-stock-span/"},
        {id:"sq14", title:"Celebrity Problem",                  day:56, difficulty:"Medium", link:"https://takeuforward.org/data-structure/the-celebrity-problem/"},
        {id:"sq15", title:"Asteroid Collision",                 day:56, difficulty:"Medium", link:"https://takeuforward.org/data-structure/asteroid-collision/"},
      ]},
    { step:9,  title:"Trees (Binary Tree + BST)",        days:"57–66", icon:"🌳", color:"#34d399",
      subtopics:[
        {id:"t1",  title:"Introduction to Trees",                day:57, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/introduction-to-trees/"},
        {id:"t2",  title:"Inorder / Preorder / Postorder",       day:57, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/inorder-preorder-postorder-traversals-in-one-traversal/"},
        {id:"t3",  title:"Level Order Traversal (BFS)",          day:57, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/level-order-traversal-of-a-binary-tree/"},
        {id:"t4",  title:"Height of Binary Tree",                day:58, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/height-of-a-binary-tree/"},
        {id:"t5",  title:"Check Balanced Binary Tree",           day:58, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/check-if-the-binary-tree-is-balanced-binary-tree/"},
        {id:"t6",  title:"Diameter of Binary Tree",              day:58, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/diameter-of-binary-tree/"},
        {id:"t7",  title:"Maximum Path Sum",                     day:59, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/maximum-sum-path-in-binary-tree/"},
        {id:"t8",  title:"Check Identical Trees",                day:59, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/check-if-two-trees-are-identical/"},
        {id:"t9",  title:"Zigzag Level Order Traversal",         day:59, difficulty:"Medium", link:"https://takeuforward.org/data-structure/zigzag-traversal-of-binary-tree/"},
        {id:"t10", title:"Boundary Traversal",                   day:60, difficulty:"Medium", link:"https://takeuforward.org/data-structure/boundary-traversal-of-a-binary-tree/"},
        {id:"t11", title:"Vertical Order Traversal",             day:60, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/vertical-order-traversal-of-binary-tree/"},
        {id:"t12", title:"Symmetric Binary Tree",                day:60, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/check-for-symmetrical-binary-tree/"},
        {id:"t13", title:"LCA of Binary Tree",                   day:61, difficulty:"Medium", link:"https://takeuforward.org/data-structure/lca-in-binary-tree/"},
        {id:"t14", title:"Maximum Width of Binary Tree",         day:61, difficulty:"Medium", link:"https://takeuforward.org/data-structure/maximum-width-of-a-binary-tree/"},
        {id:"t15", title:"Children Sum Property",                day:61, difficulty:"Medium", link:"https://takeuforward.org/data-structure/check-for-children-sum-property-in-a-binary-tree/"},
        {id:"t16", title:"Print All Root to Leaf Paths",         day:62, difficulty:"Medium", link:"https://takeuforward.org/data-structure/print-root-to-node-path-in-a-binary-tree/"},
        {id:"t17", title:"Construct BT from Inorder+Preorder",  day:62, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/construct-a-binary-tree-from-inorder-and-preorder-traversal/"},
        {id:"t18", title:"Flatten BT to Linked List",            day:63, difficulty:"Medium", link:"https://takeuforward.org/data-structure/flatten-binary-tree-to-linked-list/"},
        {id:"t19", title:"Morris Inorder Traversal",             day:63, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/morris-inorder-traversal-of-a-binary-tree/"},
        {id:"t20", title:"Search in BST",                        day:64, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/search-in-a-binary-search-tree-explained/"},
        {id:"t21", title:"Ceil/Floor in BST",                    day:64, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/ceil-in-a-binary-search-tree/"},
        {id:"t22", title:"Insert in BST",                        day:64, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/insert-a-node-in-a-binary-search-tree/"},
        {id:"t23", title:"Delete in BST",                        day:65, difficulty:"Medium", link:"https://takeuforward.org/data-structure/delete-a-node-in-binary-search-tree/"},
        {id:"t24", title:"Kth Smallest Element in BST",          day:65, difficulty:"Medium", link:"https://takeuforward.org/data-structure/kth-largest-smallest-element-in-binary-search-tree/"},
        {id:"t25", title:"Validate BST",                         day:65, difficulty:"Medium", link:"https://takeuforward.org/data-structure/validate-binary-search-tree/"},
        {id:"t26", title:"LCA in BST",                           day:66, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/lca-in-a-binary-search-tree/"},
        {id:"t27", title:"Construct BST from Preorder",          day:66, difficulty:"Medium", link:"https://takeuforward.org/data-structure/construct-a-bst-from-a-preorder-traversal/"},
      ]},
    { step:10, title:"Heaps (Priority Queue)",           days:"67–69", icon:"⛰️", color:"#f87171",
      subtopics:[
        {id:"h1", title:"Implement Min/Max Heap",         day:67, difficulty:"Medium", link:"https://takeuforward.org/data-structure/implementation-of-priority-queue-using-binary-heap/"},
        {id:"h2", title:"Kth Largest Element in Array",   day:67, difficulty:"Medium", link:"https://takeuforward.org/data-structure/kth-largest-element-in-an-array/"},
        {id:"h3", title:"Kth Largest Element in Stream",  day:67, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/kth-largest-element-in-a-stream/"},
        {id:"h4", title:"Maximum Sum Combinations",       day:68, difficulty:"Medium", link:"https://takeuforward.org/data-structure/maximum-sum-combinations/"},
        {id:"h5", title:"Find Median from Data Stream",   day:68, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/find-median-from-data-stream/"},
        {id:"h6", title:"K Most Frequent Elements",       day:69, difficulty:"Medium", link:"https://takeuforward.org/data-structure/top-k-frequent-elements/"},
        {id:"h7", title:"Task Scheduler",                 day:69, difficulty:"Medium", link:"https://takeuforward.org/data-structure/task-scheduler/"},
      ]},
    { step:11, title:"Graphs",                           days:"70–78", icon:"🕸️", color:"#818cf8",
      subtopics:[
        {id:"g1",  title:"Graph Representation",              day:70, difficulty:"Easy",   link:"https://takeuforward.org/graph/graph-and-its-representations-adjacency-matrix-and-adjacency-list/"},
        {id:"g2",  title:"BFS of Graph",                      day:70, difficulty:"Easy",   link:"https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/"},
        {id:"g3",  title:"DFS of Graph",                      day:70, difficulty:"Easy",   link:"https://takeuforward.org/graph/depth-first-search-dfs-traversal/"},
        {id:"g4",  title:"Number of Connected Components",    day:71, difficulty:"Easy",   link:"https://takeuforward.org/graph/connected-components-problem-in-graph/"},
        {id:"g5",  title:"Detect Cycle (Undirected — BFS)",   day:71, difficulty:"Medium", link:"https://takeuforward.org/graph/detect-cycle-in-an-undirected-graph-using-bfs/"},
        {id:"g6",  title:"Detect Cycle (Directed — DFS)",     day:71, difficulty:"Medium", link:"https://takeuforward.org/graph/detect-cycle-in-directed-graph-using-dfs/"},
        {id:"g7",  title:"Topological Sort (DFS)",            day:72, difficulty:"Medium", link:"https://takeuforward.org/graph/topological-sort-using-dfs/"},
        {id:"g8",  title:"Topological Sort (Kahn's BFS)",     day:72, difficulty:"Medium", link:"https://takeuforward.org/graph/kahns-algorithm-topological-sort-algorithm-bfs/"},
        {id:"g9",  title:"Shortest Path in DAG",              day:72, difficulty:"Medium", link:"https://takeuforward.org/graph/shortest-path-in-directed-acyclic-graph-topological-sort/"},
        {id:"g10", title:"Shortest Path Undirected (BFS)",    day:73, difficulty:"Easy",   link:"https://takeuforward.org/graph/shortest-path-in-undirected-graph-with-unit-weights/"},
        {id:"g11", title:"Dijkstra's Algorithm",              day:73, difficulty:"Medium", link:"https://takeuforward.org/graph/dijkstras-algorithm-using-set-priority-queue/"},
        {id:"g12", title:"Bellman Ford Algorithm",            day:74, difficulty:"Medium", link:"https://takeuforward.org/graph/bellman-ford-algorithm/"},
        {id:"g13", title:"Floyd Warshall Algorithm",          day:74, difficulty:"Hard",   link:"https://takeuforward.org/graph/floyd-warshall-algorithm/"},
        {id:"g14", title:"Prim's MST Algorithm",              day:75, difficulty:"Medium", link:"https://takeuforward.org/graph/prims-algorithm-minimum-spanning-tree/"},
        {id:"g15", title:"Kruskal's MST (DSU)",               day:75, difficulty:"Medium", link:"https://takeuforward.org/graph/kruskals-algorithm-minimum-spanning-tree/"},
        {id:"g16", title:"Number of Islands",                 day:76, difficulty:"Medium", link:"https://takeuforward.org/graph/number-of-islands/"},
        {id:"g17", title:"Bipartite Graph Check",             day:76, difficulty:"Medium", link:"https://takeuforward.org/graph/bipartite-check-using-bfs/"},
        {id:"g18", title:"Course Schedule",                   day:77, difficulty:"Medium", link:"https://takeuforward.org/graph/course-schedule-i/"},
        {id:"g19", title:"Word Ladder",                       day:77, difficulty:"Hard",   link:"https://takeuforward.org/graph/word-ladder-i/"},
        {id:"g20", title:"Strongly Connected Components",     day:78, difficulty:"Hard",   link:"https://takeuforward.org/graph/strongly-connected-components-kosarajus-algorithm/"},
      ]},
    { step:12, title:"Dynamic Programming",              days:"79–88", icon:"⚡", color:"#f59e0b",
      subtopics:[
        {id:"dp1",  title:"Intro to DP + Memoization",                day:79, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/introduction-to-dynamic-programming/"},
        {id:"dp2",  title:"Climbing Stairs",                          day:79, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/dynamic-programming-introduction/"},
        {id:"dp3",  title:"Frog Jump",                                day:79, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/dynamic-programming-frog-jump/"},
        {id:"dp4",  title:"House Robber",                             day:80, difficulty:"Medium", link:"https://takeuforward.org/data-structure/house-robber-dp-on-subsequences/"},
        {id:"dp5",  title:"Longest Increasing Subsequence",           day:80, difficulty:"Medium", link:"https://takeuforward.org/data-structure/longest-increasing-subsequence-dp-41/"},
        {id:"dp6",  title:"0/1 Knapsack Problem",                     day:81, difficulty:"Medium", link:"https://takeuforward.org/data-structure/0-1-knapsack-dp-19/"},
        {id:"dp7",  title:"Unbounded Knapsack",                       day:81, difficulty:"Medium", link:"https://takeuforward.org/data-structure/unbounded-knapsack-dp-23/"},
        {id:"dp8",  title:"Coin Change (Minimum Coins)",              day:82, difficulty:"Medium", link:"https://takeuforward.org/data-structure/coin-change-minimum-number-of-coins/"},
        {id:"dp9",  title:"Coin Change 2 (Number of Ways)",           day:82, difficulty:"Medium", link:"https://takeuforward.org/data-structure/coin-change-2-dp-15/"},
        {id:"dp10", title:"Longest Common Subsequence",               day:83, difficulty:"Medium", link:"https://takeuforward.org/data-structure/longest-common-subsequence-dp-25/"},
        {id:"dp11", title:"Edit Distance",                            day:83, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/edit-distance-dp-33/"},
        {id:"dp12", title:"Longest Palindromic Subsequence",          day:84, difficulty:"Medium", link:"https://takeuforward.org/data-structure/longest-palindromic-subsequence-dp-28/"},
        {id:"dp13", title:"Matrix Chain Multiplication",              day:84, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/matrix-chain-multiplication-dp-48/"},
        {id:"dp14", title:"Burst Balloons",                           day:85, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/burst-balloons-dp-51/"},
        {id:"dp15", title:"Maximum Rectangle in Binary Matrix",       day:85, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/maximal-rectangle-area-in-binary-matrix-dp/"},
        {id:"dp16", title:"Buy & Sell Stock (Multiple Transactions)", day:86, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/buy-and-sell-stock-dp-35/"},
        {id:"dp17", title:"Buy & Sell Stock with Cooldown",           day:86, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/buy-and-sell-stock-with-cooldown-dp-39/"},
        {id:"dp18", title:"Partition Equal Subset Sum",               day:87, difficulty:"Medium", link:"https://takeuforward.org/data-structure/partition-equal-subset-sum-dp-15/"},
        {id:"dp19", title:"Egg Drop Problem",                         day:87, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/egg-drop-dp-58/"},
        {id:"dp20", title:"Wildcard Matching",                        day:88, difficulty:"Hard",   link:"https://takeuforward.org/data-structure/wildcard-matching-dp-34/"},
      ]},
    { step:13, title:"Greedy + Sliding Window + Two Pointer", days:"89–90", icon:"🎯", color:"#38bdf8",
      subtopics:[
        {id:"gw1", title:"Assign Cookies (Greedy)",            day:89, difficulty:"Easy",   link:"https://takeuforward.org/data-structure/assign-cookies/"},
        {id:"gw2", title:"Jump Game I",                        day:89, difficulty:"Medium", link:"https://takeuforward.org/data-structure/jump-game/"},
        {id:"gw3", title:"Jump Game II",                       day:89, difficulty:"Medium", link:"https://takeuforward.org/data-structure/jump-game-2/"},
        {id:"gw4", title:"Minimum Platforms (Greedy)",         day:89, difficulty:"Medium", link:"https://takeuforward.org/data-structure/minimum-number-of-platforms-required-for-a-railway/"},
        {id:"gw5", title:"Two Pointer — 3Sum",                 day:90, difficulty:"Medium", link:"https://takeuforward.org/data-structure/3-sum-find-triplets-that-add-up-to-a-zero/"},
        {id:"gw6", title:"Sliding Window — Max Sum Subarray",  day:90, difficulty:"Medium", link:"https://takeuforward.org/data-structure/maximum-sum-subarray-of-size-k/"},
        {id:"gw7", title:"Sliding Window — Longest Substring", day:90, difficulty:"Medium", link:"https://takeuforward.org/data-structure/length-of-longest-substring-without-any-repeating-character/"},
      ]},
  ]
};
DSA_PLAN.totalProblems = DSA_PLAN.topics.reduce((s,t) => s + t.subtopics.length, 0);
EOF
echo "dsa done"
Output

dsa done
