const ROADMAP = {
  startDate: "2026-06-11",
  totalVideos: 311,
  totalDays: 77,
  totalProjects: 12,

  days: {
    // WEEK 1 — Sheryians Python
    1: { playlist:"Sheryians", topics:["Python Basics","Variables","Data Types"], targetVideos:3, targetHours:6, practice:"FizzBuzz" },
    2: { playlist:"Sheryians", topics:["Control Flow","Loops","Functions"], targetVideos:2, targetHours:4, practice:"Custom Functions" },
    3: { playlist:"Sheryians", topics:["OOP","Classes","Inheritance"], targetVideos:2, targetHours:4, practice:"Bank Account Class" },
    4: { playlist:"Sheryians", topics:["Decorators","Generators","Exceptions"], targetVideos:2, targetHours:4, practice:"Logging Decorator" },
    5: { playlist:"Sheryians", topics:["NumPy Arrays","Indexing","Reshaping"], targetVideos:2, targetHours:4, practice:"Matrix Operations" },
    6: { playlist:"Sheryians", topics:["Pandas DataFrames","GroupBy","Merging"], targetVideos:2, targetHours:4, practice:"CSV Analysis" },
    7: { playlist:"Sheryians", topics:["Matplotlib","Seaborn","EDA Practice"], targetVideos:2, targetHours:4, practice:"Titanic EDA Notebook" },
    // WEEK 2 — 100 Days ML
    8:  { playlist:"100 Days ML", topics:["ML Intro","Supervised vs Unsupervised","sklearn Basics"], targetVideos:3, targetHours:2.5, practice:"Iris Classification" },
    9:  { playlist:"100 Days ML", topics:["Linear Regression","MSE Loss","Gradient Descent"], targetVideos:3, targetHours:2.5, practice:"Salary Predictor" },
    10: { playlist:"100 Days ML", topics:["Logistic Regression","Binary Classification","Sigmoid"], targetVideos:3, targetHours:2.5, practice:"Spam Detector" },
    11: { playlist:"100 Days ML", topics:["Train/Test Split","Cross Validation","Overfitting"], targetVideos:3, targetHours:2.5, practice:"Bias-Variance Analysis" },
    12: { playlist:"100 Days ML", topics:["Feature Engineering","Encoding","Scaling"], targetVideos:3, targetHours:2.5, practice:"Feature Pipeline" },
    13: { playlist:"100 Days ML", topics:["Decision Trees","Gini Impurity","Pruning"], targetVideos:3, targetHours:2.5, practice:"Titanic DT" },
    14: { playlist:"100 Days ML", topics:["Random Forest","Bagging","Feature Importance"], targetVideos:2, targetHours:2, practice:"Toy ML Project" },
    // WEEK 3
    15: { playlist:"100 Days ML", topics:["SVM","Kernels","Hyperplanes"], targetVideos:4, targetHours:3, practice:"SVM Classifier" },
    16: { playlist:"100 Days ML", topics:["KNN","Distance Metrics","KD Trees"], targetVideos:4, targetHours:3, practice:"KNN Regressor" },
    17: { playlist:"100 Days ML", topics:["Naive Bayes","Bayes Theorem","Text Classification"], targetVideos:4, targetHours:3, practice:"News Classifier" },
    18: { playlist:"100 Days ML", topics:["Clustering","K-Means","DBSCAN"], targetVideos:5, targetHours:4, practice:"Customer Segmentation" },
    19: { playlist:"100 Days ML", topics:["PCA","Dimensionality Reduction","t-SNE"], targetVideos:4, targetHours:3, practice:"PCA Visualizer" },
    20: { playlist:"100 Days ML", topics:["Hyperparameter Tuning","GridSearchCV","RandomSearch"], targetVideos:5, targetHours:4, practice:"Tuning Lab" },
    21: { playlist:"100 Days ML", topics:["Pipelines","ColumnTransformer","Model Export"], targetVideos:4, targetHours:3, practice:"House Prices Pipeline" },
    // WEEK 4
    22: { playlist:"100 Days ML", topics:["Gradient Boosting","XGBoost Intro","Boosting Theory"], targetVideos:4, targetHours:3, practice:"XGBoost Baseline" },
    23: { playlist:"100 Days ML", topics:["XGBoost Tuning","Early Stopping","Feature Importance"], targetVideos:5, targetHours:4, practice:"XGB Advanced" },
    24: { playlist:"100 Days ML", topics:["LightGBM","CatBoost","Ensemble Stacking"], targetVideos:5, targetHours:4, practice:"Stacking Model" },
    25: { playlist:"100 Days ML", topics:["Model Evaluation","ROC-AUC","Precision-Recall"], targetVideos:4, targetHours:3, practice:"Evaluation Suite" },
    26: { playlist:"100 Days ML", topics:["Imbalanced Data","SMOTE","Class Weights"], targetVideos:4, targetHours:3, practice:"Resampling Lab" },
    27: { playlist:"100 Days ML", topics:["Linear Regression From Scratch","Math Derivation","Vectorized"], targetVideos:4, targetHours:3, practice:"LR From Scratch" },
    28: { playlist:"100 Days ML", topics:["Logistic Regression From Scratch","Backprop","Viz"], targetVideos:4, targetHours:4, practice:"Linear Regression From Scratch" },
    // WEEK 5
    29: { playlist:"100 Days ML", topics:["Time Series Intro","Stationarity","ACF/PACF"], targetVideos:7, targetHours:3, practice:"TS Analysis" },
    30: { playlist:"100 Days ML", topics:["ARIMA","SARIMA","Forecasting"], targetVideos:8, targetHours:3.5, practice:"Stock Forecast" },
    31: { playlist:"100 Days ML", topics:["Anomaly Detection","IsolationForest","LOF"], targetVideos:8, targetHours:3.5, practice:"Anomaly Lab" },
    32: { playlist:"100 Days ML", topics:["Fraud Detection Dataset","EDA","Class Balance"], targetVideos:8, targetHours:3.5, practice:"Fraud EDA" },
    33: { playlist:"100 Days ML", topics:["Fraud Model Building","Ensemble","Threshold Tuning"], targetVideos:8, targetHours:3.5, practice:"Fraud Model" },
    34: { playlist:"100 Days ML", topics:["Fraud Platform UI","FastAPI","Deployment Prep"], targetVideos:8, targetHours:4, practice:"Fraud API" },
    35: { playlist:"100 Days ML", topics:["Render Deployment","GitHub Actions","CI/CD"], targetVideos:7, targetHours:4, practice:"Fraud Detection Platform" },
    // WEEK 6 — Deep Learning
    36: { playlist:"100 Days DL", topics:["Neural Networks Intro","Perceptron","Activation Fns"], targetVideos:6, targetHours:4, practice:"Perceptron Lab" },
    37: { playlist:"100 Days DL", topics:["Backpropagation","Chain Rule","Gradient Flow"], targetVideos:6, targetHours:4, practice:"Backprop Math" },
    38: { playlist:"100 Days DL", topics:["Keras/TensorFlow Basics","Sequential API","Dense Layers"], targetVideos:6, targetHours:4, practice:"Keras Hello World" },
    39: { playlist:"100 Days DL", topics:["Loss Functions","Optimizers","Learning Rate"], targetVideos:6, targetHours:4, practice:"Optimizer Comparison" },
    40: { playlist:"100 Days DL", topics:["Regularization","Dropout","BatchNorm"], targetVideos:6, targetHours:4, practice:"Regularization Lab" },
    41: { playlist:"100 Days DL", topics:["ANN From Scratch","NumPy Only","Forward + Backprop"], targetVideos:6, targetHours:4, practice:"ANN NumPy" },
    42: { playlist:"100 Days DL", topics:["CNN Basics","Conv Layers","Pooling","ANN Polish"], targetVideos:6, targetHours:4, practice:"ANN From Scratch" },
    // WEEK 7
    43: { playlist:"100 Days DL", topics:["CNN Architecture","AlexNet","VGG","ResNet"], targetVideos:6, targetHours:4, practice:"Transfer Learning" },
    44: { playlist:"100 Days DL", topics:["Object Detection Intro","Anchor Boxes","YOLO Theory"], targetVideos:6, targetHours:4, practice:"Detection Theory" },
    45: { playlist:"100 Days DL", topics:["YOLOv10 Setup","Ultralytics","Training Config"], targetVideos:6, targetHours:4, practice:"YOLOv10 Train" },
    46: { playlist:"100 Days DL", topics:["YOLOv10 Custom Dataset","Labeling","Roboflow"], targetVideos:6, targetHours:4, practice:"Custom Dataset" },
    47: { playlist:"100 Days DL", topics:["YOLOv10 Evaluation","mAP","Inference Speed"], targetVideos:6, targetHours:4, practice:"Model Evaluation" },
    48: { playlist:"100 Days DL", topics:["RNN Intro","Vanishing Gradient","LSTM Basics"], targetVideos:6, targetHours:3, practice:"RNN Sequence" },
    49: { playlist:"100 Days DL", topics:["YOLOv10 Deployment","Streamlit","Demo App"], targetVideos:6, targetHours:4, practice:"YOLOv10 Project" },
    // WEEK 8 — NLP + LangChain
    50: { playlist:"NLP", topics:["NLP Fundamentals","Tokenization","Stemming/Lemmatization"], targetVideos:2, targetHours:2, practice:"Text Preprocessing" },
    51: { playlist:"NLP", topics:["TF-IDF","Word2Vec","Embeddings"], targetVideos:2, targetHours:2, practice:"Embedding Lab" },
    52: { playlist:"NLP", topics:["Transformers Intro","Attention Mechanism","BERT Overview"], targetVideos:2, targetHours:2, practice:"HuggingFace Basics" },
    53: { playlist:"NLP", topics:["Text Classification","Named Entity Recognition","Sentiment"], targetVideos:2, targetHours:2, practice:"NLP Pipeline" },
    54: { playlist:"LangChain", topics:["LangChain Intro","Chains","Prompts","LLM Wrappers"], targetVideos:5, targetHours:4, practice:"First Chain" },
    55: { playlist:"LangChain", topics:["RAG Architecture","VectorStores","FAISS","Chroma"], targetVideos:5, targetHours:4, practice:"RAG Pipeline" },
    56: { playlist:"LangChain", topics:["RAG Chatbot Build","Memory","Retrieval","UI"], targetVideos:5, targetHours:5, practice:"RAG Chatbot" },
    // WEEK 9 — LangGraph + FastAPI
    57: { playlist:"LangGraph", topics:["LangGraph Intro","Nodes","Edges","StateGraph"], targetVideos:6, targetHours:4, practice:"Simple Graph" },
    58: { playlist:"LangGraph", topics:["Agent Design","Tools","ReAct Pattern"], targetVideos:6, targetHours:4, practice:"ReAct Agent" },
    59: { playlist:"LangGraph", topics:["Multi-Agent Systems","Supervisor","Handoffs"], targetVideos:5, targetHours:4, practice:"Multi-Agent" },
    60: { playlist:"LangGraph", topics:["Conditional Edges","Interrupts","Human-in-Loop"], targetVideos:5, targetHours:4, practice:"HITL Flow" },
    61: { playlist:"FastAPI", topics:["FastAPI Basics","Routing","Pydantic Models"], targetVideos:3, targetHours:2, practice:"Hello FastAPI" },
    62: { playlist:"FastAPI", topics:["FastAPI + ML Models","Async","Background Tasks"], targetVideos:3, targetHours:2, practice:"ML Endpoint" },
    63: { playlist:"FastAPI", topics:["FastAPI + LangGraph","Agent + API","Deployment"], targetVideos:4, targetHours:3, practice:"Agent + FastAPI API" },
    // WEEK 10 — MCP + Revision
    64: { playlist:"MCP", topics:["MCP Protocol Intro","Servers","Clients","Tools"], targetVideos:2, targetHours:2, practice:"MCP Concepts" },
    65: { playlist:"MCP", topics:["MCP Server Build","Tool Registration","Testing"], targetVideos:2, targetHours:2, practice:"First MCP Tool" },
    66: { playlist:"MCP", topics:["MCP + Claude Integration","Deployment","Hosting"], targetVideos:2, targetHours:2, practice:"MCP Server" },
    67: { playlist:"MCP", topics:["MCP Advanced","Streaming","Auth","Error Handling"], targetVideos:2, targetHours:1, practice:"MCP Polish" },
    68: { playlist:"Revision", topics:["ML Concepts Review","Flash Cards","Mock Q&A"], targetVideos:0, targetHours:4, practice:"ML Quiz" },
    69: { playlist:"Revision", topics:["DL Concepts Review","CNN/RNN Summary","Key Formulas"], targetVideos:0, targetHours:4, practice:"DL Quiz" },
    70: { playlist:"Revision", topics:["LLMs/LangChain Review","RAG Patterns","Agent Design"], targetVideos:0, targetHours:4, practice:"LLM Quiz" },
    // WEEK 11 — Interview Prep
    71: { playlist:"Interview Prep", topics:["DSA — Arrays & Strings","LeetCode Easy x5","Pattern Recognition"], targetVideos:0, targetHours:6, practice:"LeetCode Sprint" },
    72: { playlist:"Interview Prep", topics:["DSA — Trees & Graphs","BFS/DFS","Shortest Path"], targetVideos:0, targetHours:6, practice:"Graph Problems" },
    73: { playlist:"Interview Prep", topics:["ML System Design","Feature Stores","Model Serving"], targetVideos:0, targetHours:6, practice:"System Design Mock" },
    74: { playlist:"Interview Prep", topics:["Behavioral Prep","STAR Method","Projects Walkthrough"], targetVideos:0, targetHours:4, practice:"Mock Interview" },
    75: { playlist:"Interview Prep", topics:["SQL Advanced","Window Functions","CTEs","Query Optimization"], targetVideos:0, targetHours:4, practice:"SQL Challenges" },
    76: { playlist:"Interview Prep", topics:["Portfolio Polish","GitHub README","LinkedIn Update"], targetVideos:0, targetHours:4, practice:"Portfolio Update" },
    77: { playlist:"Interview Prep", topics:["Final Review","Rest","Confidence Mode 🚀"], targetVideos:0, targetHours:3, practice:"You're Ready!" },
  },

  playlists: [
    { id:1, name:"Sheryians",       videos:15,  hours:24,   startWeek:1,  endWeek:1 },
    { id:2, name:"100 Days ML",     videos:134, hours:62.8, startWeek:2,  endWeek:5 },
    { id:3, name:"100 Days DL",     videos:84,  hours:52.2, startWeek:6,  endWeek:7 },
    { id:4, name:"NLP",             videos:8,   hours:9.6,  startWeek:8,  endWeek:8 },
    { id:5, name:"LangChain",       videos:21,  hours:21.9, startWeek:8,  endWeek:8 },
    { id:6, name:"LangGraph",       videos:28,  hours:23.7, startWeek:9,  endWeek:9 },
    { id:7, name:"FastAPI",         videos:13,  hours:8.9,  startWeek:9,  endWeek:9 },
    { id:8, name:"MCP",             videos:8,   hours:7.1,  startWeek:10, endWeek:10 },
  ],

  weeks: {
    1:  { playlist:"Sheryians",           dateRange:"11 Jun – 17 Jun 2026",  targetVideos:15,  targetHours:24,  deliverable:"Titanic EDA Notebook" },
    2:  { playlist:"100 Days ML",         dateRange:"18 Jun – 24 Jun 2026",  targetVideos:20,  targetHours:16,  deliverable:"Toy ML Project" },
    3:  { playlist:"100 Days ML",         dateRange:"25 Jun – 1 Jul 2026",   targetVideos:30,  targetHours:22,  deliverable:"House Prices Pipeline" },
    4:  { playlist:"100 Days ML",         dateRange:"2 Jul – 8 Jul 2026",    targetVideos:30,  targetHours:20,  deliverable:"Linear Regression From Scratch" },
    5:  { playlist:"100 Days ML",         dateRange:"9 Jul – 15 Jul 2026",   targetVideos:54,  targetHours:24,  deliverable:"Fraud Detection Platform" },
    6:  { playlist:"100 Days DL",         dateRange:"16 Jul – 22 Jul 2026",  targetVideos:42,  targetHours:26,  deliverable:"ANN From Scratch" },
    7:  { playlist:"100 Days DL",         dateRange:"23 Jul – 29 Jul 2026",  targetVideos:42,  targetHours:26,  deliverable:"YOLOv10 Project" },
    8:  { playlist:"NLP + LangChain",     dateRange:"30 Jul – 5 Aug 2026",   targetVideos:29,  targetHours:31,  deliverable:"RAG Chatbot" },
    9:  { playlist:"LangGraph + FastAPI", dateRange:"6 Aug – 12 Aug 2026",   targetVideos:41,  targetHours:33,  deliverable:"Agent + FastAPI API" },
    10: { playlist:"MCP + Revision",      dateRange:"13 Aug – 19 Aug 2026",  targetVideos:8,   targetHours:17,  deliverable:"MCP Server" },
    11: { playlist:"Interview Prep",      dateRange:"20 Aug – 8 Sep 2026",   targetVideos:0,   targetHours:33,  deliverable:"Interview Ready 🚀" },
  },

  projects: [
    { id:1,  name:"AI Fraud Detection Platform",    status:"Completed",   week:5 },
    { id:2,  name:"YOLOv10 Weapon Detection",       status:"Completed",   week:7 },
    { id:3,  name:"PAN Validation Engine",          status:"Completed",   week:1 },
    { id:4,  name:"Titanic EDA Pipeline",           status:"Not Started", week:1 },
    { id:5,  name:"House Prices ML Pipeline",       status:"Not Started", week:3 },
    { id:6,  name:"Linear Regression From Scratch", status:"Not Started", week:4 },
    { id:7,  name:"ANN From Scratch",               status:"Not Started", week:6 },
    { id:8,  name:"Image Classifier",               status:"Not Started", week:7 },
    { id:9,  name:"RAG Chatbot",                    status:"Not Started", week:8 },
    { id:10, name:"LangGraph Agent",                status:"Not Started", week:9 },
    { id:11, name:"FastAPI ML Deployment",          status:"Not Started", week:9 },
    { id:12, name:"MCP Server",                     status:"Not Started", week:10 },
  ],
};
